import type { Metadata } from "next";
import "./globals.css";

import LocalFont from "next/font/local";

const inter = LocalFont({
  src: [
    {
      path: "../../public/font/0_BlackerSansProVariableGX.ttf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../public/font/0_BlackerSansProVariableGX.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/font/0_BlackerSansProVariableGX.ttf",
      weight: "400",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
