import type { Metadata, Viewport } from "next";
import "./globals.css";

import LocalFont from "next/font/local";
import StyledComponentsRegistry from "@/app/lib/registry";

const inter = LocalFont({
  src: [
    {
      path: "../../public/font/0_BlackerSansProVariableGX.ttf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../public/font/0_BlackerSansProVariableGX.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/font/0_BlackerSansProVariableGX.ttf",
      weight: "400",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Фасады Сысолы",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  initialScale: 1,
  width: "device-width",
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          {children}
          <div id="Modal"></div>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
